// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import ImportModalController from "./import_modal_controller"
application.register("import-modal", ImportModalController)