// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EstoqueFormController from "./estoque_form_controller"
application.register("estoque-form", EstoqueFormController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import ImportModalController from "./import_modal_controller"
application.register("import-modal", ImportModalController)

import FormasRecebimentoChartController from "./formas_recebimento_chart_controller"
application.register("formas-recebimento-chart", FormasRecebimentoChartController)